### ISSUE TITLE
easier-tags

### ISSUE THREAD

**Issue by infpreddit** [Amnesthesia/Robobelle#18]
Setting a tag makes the set word function as a standard command and eliminates the need for the !get command. IE, !lol instead of !get lol.

**Comment by Amnesthesia** [comment]
I don't think this is actually possible without making her _really_ slow :( She would have to check every !command against the entire list of tags everytime, and if one matches, pull it out - it'd be really slow to use any command :(

**Comment by ithil** [comment]
How about this:
- Approach 1) Commands have priority; so if a command, say `!greet`, exists she simply executes it and nothing else happens. If, however, the command does not exist she looks for a tag with that name and pulls it out instead.
- Approach 2) Create a special prefix for tags, for example `!!`. So `!!lol` would be equivalent to `!get lol`.
